env:
    node: true
    es6: true
    mocha: true
extends:
    - airbnb-base
globals:
    expect: true
    describe: true
    it: true
rules:
    import/no-extraneous-dependencies: 0
    object-curly-newline: 0
    no-unused-expressions: 0
    no-underscore-dangle: 0
